name: "Podcast Generator"

author: "Barrack Amuyunzu"
description: "Generate a feed for a podcast "

runs:
  using: "Docker"
  iamge: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: The commiters Email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The Commiters Name
    required: true
    default: ${{ github.actor }}